### ISSUE TITLE
Remove dependency on Harvest Finance APIs

### ISSUE THREAD

**Issue by brandoncurtis** [harvestfi/dashboard#19]
We should avoid adding dependencies on the Harvest Finance official API.  One of the points of having a third-party dashboard is that anybody can download and run it to manage their positions without relying on official data that may be manipulated, changed in format, or offline.  If we need APYs, get them directly from the chain like https://github.com/harvestfi/harvest-discordbot does.

**Comment by belbix** [comment]
https://www.notion.so/harvestfinance/DASH-Remove-token-API-from-code-e1af8c095b1f4be88388a35de9c77989

**Comment by belbix** [comment]
https://www.notion.so/harvestfinance/DASH-Create-independent-APY-calculation-9144a1c8ffac4dffa2a23737fc2ec84c
