### ISSUE TITLE
Potential double-calling (to Infura)

### ISSUE THREAD

**Issue by s-ilic** [harvestfi/dashboard#21]
Upgrading to the latest commit (43fdf5c2f189c673e1a6c0056825e4a3e2f2845e) from an older one (8a95b6d36b5034e6e03fcbe5787701878fad7fec) resulted in almost exactly doubling the number of calls made to Infura when I'm using the track.js script from the "scripts" folder.

Wondering if any new feature may have caused this, or if this may be a bug ?

**Comment by belbix** [comment]
https://www.notion.so/harvestfinance/DASH-Potential-double-calling-to-Infura-d5cd678b600645dc8fb29f6ebda584ff

**Comment by belbix** [comment]
out of date
