### ISSUE TITLE
Show historical FARM earned

### ISSUE THREAD

**Issue by silagepete** [harvestfi/dashboard#36]

**Comment by belbix** [comment]
I created an endpoint https://api.farmdashboard.xyz:4140/last/hardwork
`{
"id": "0x565c1228f23fcbce679686aa534781d2976b1ba9df7edea5ec91565b4f255cef_290",
"vault": "USDC",
"block": 11496281,
"blockDate": 1608547453,
"shareChange": 0.000098,
"shareChangeUsd": 6087.885064494772,
"shareUsdTotal": 440765.4062442312,
"tvl": 52664554,
"allProfit": 9651765.690682929,
"periodOfWork": 5333240,
"psPeriodOfWork": 9195921,
"perc": 0.01155973914541225,
"apr": 7.234643556526596,
"weeklyProfit": 222376.59565301955,
"weeklyAllProfit": 884631.383829434,
"psTvlUsd": 27402295.1908179,
"psApr": 51.80262650212215,
"farmBuyback": 22.601557065947183,
"farmBuybackSum": 36626.4342624445
}`

You can use farmBuybackSum value for this purpose

**Comment by belbix** [comment]
https://www.notion.so/harvestfinance/DASH-Show-historical-FARM-earned-e6d34927bbc9495f981a2d9bee599e17

**Comment by belbix** [comment]
implemented in https://github.com/harvestfi/dashboard/pull/42
