### ISSUE TITLE
Radio is covered by the staked assets panel in read only mode

### ISSUE THREAD

**Issue by silagepete** [harvestfi/dashboard#41]
![image](https://user-images.githubusercontent.com/70731022/103162842-87020100-47aa-11eb-9afe-acca5af2207c.png)

**Comment by belbix** [comment]
https://www.notion.so/harvestfinance/DASH-Fix-radio-in-read-only-mode-09e2b92e7639496f833f36424e8a70dc

**Comment by belbix** [comment]
fixed in https://github.com/harvestfi/dashboard/pull/47
