### ISSUE TITLE
Switch wallets when Metamask wallet is switched

### ISSUE THREAD

**Issue by brandoncurtis** [harvestfi/dashboard#6]
If you switch wallets in Metamask, there is no way to also switch wallets in the app.

Add a "switch wallet" button or listen for wallet changes and do this automagically.

**Comment by Byron-McKeeby** [comment]
https://docs.metamask.io/guide/ethereum-provider.html#events

**Comment by Byron-McKeeby** [comment]
closed in latest `main`
