### ISSUE TITLE
incorrect balance is being displayed for F1INCH-ETH:WBTC Farm

### ISSUE THREAD

**Issue by io2** [harvestfi/dashboard#62]
Hi there,

Trying out Harvest Finance and after having deposited and staked my LP tokens, I notice the  value shown for the F1INCH-ETH:WBTC is significantly off.  

![Screenshot_20210121_161211](https://user-images.githubusercontent.com/60398/105370035-7014ca00-5c03-11eb-8648-c783173c74ad.png)

If someone's got a handle on this and can provide pointers on how to fix it, am happy to send a PR.

**Comment by AndreMiras** [comment]
Yeah looks like only half of the value is reported (e.g. compared to zapper.fi)

**Comment by belbix** [comment]
out of date
